### ISSUE TITLE
De qual estado vcs são?

### ISSUE THREAD

**Issue by guesant** [vuejs-norte/vuejs-norte.github.io#1]
Olaaaaaaaa galera, também sou do norte (do Brasil)... Sou do estado de Rondônia... e vcs?

**Comment by iagocavalcante** [comment]
Somos do Pará /o/

**Comment by patrickmonteiro** [comment]
Também tem uma galerinha de Manaus no grupo do wpp.

**Comment by guesant** [comment]
Posso entrar no gp?

**Comment by amimaro** [comment]
Claro!
https://chat.whatsapp.com/7gXcqLOFdYaDmO7hgeGk6I

**Comment by patrickmonteiro** [comment]
Irei fechar, porém aberto para novos comentários.
