### ISSUE TITLE
Add freeCodeCamp Belém at Local communities

### ISSUE THREAD

**Issue by oaugusto256** [vuejs-norte/vuejs-norte.github.io#2]
Add freeCodeCamp Belém at Local communities

Name: freeCodeCamp Belém

Links:
- Facebook: https://www.facebook.com/groups/free.code.camp.belem/
- Github: https://github.com/fcc-belem
- Site: https://freecodecamp.org/

**Comment by patrickmonteiro** [comment]
Added!
